name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify a precise Python version

    - name: Create virtual environment
      run: python -m venv venv

    - name: Check virtual environment
      run: ls -la venv

    - name: Install dependencies
      run: |
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to PythonAnywhere
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        . venv/bin/activate
        python deploy_to_pythonanywhere.py
